# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='level',
            field=models.CharField(default='level', max_length=128),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(default='number', max_length=12),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='name', max_length=128),
        ),
    ]
